### ISSUE TITLE
Remove sncast json workaround in DevnetClient

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/starknet.swift#113]
- [x] https://github.com/foundry-rs/starknet-foundry/issues/678
- [ ] Adjust to new `sncast` version

Blocked by: https://github.com/foundry-rs/starknet-foundry/pull/1093

**Comment by Subbitoooo** [comment]
All right,to remove the JSON workaround in StarkNet, you can use native StarkNet data types and functions instead of converting data to JSON and back. This can make your code more efficient and easier to read. Hoping that This can help you to solve your problem. If you have any question, just ask me ;) .

**Comment by DelevoXDG** [comment]
@Subbitoooo 
Hi, I'm not sure what are you referring to. 
This issue is dedicated to removing a workaround in DevnetClient (used for testing), caused by another specific issue mentioned in the description. This is a minor change and will be resolved in #114.

There are currently no any plans to refactor the way objects are serialized for interaction with JSON-RPC nodes.

**Comment by THenry14** [comment]
https://github.com/software-mansion/starknet.swift/issues/130
